# Generated by Django 4.1.3 on 2023-02-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0003_banks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='user',
        ),
        migrations.AddField(
            model_name='banks',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
