# Generated by Django 4.1.3 on 2023-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0005_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreements',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreements',
            name='requisition_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
