# Generated by Django 4.1.3 on 2023-02-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0006_agreements_user_id_alter_agreements_requisition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
