# Generated by Django 4.1.3 on 2023-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0007_alter_agreements_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreements',
            name='bank_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='banks',
            name='bank_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
