# Generated by Django 4.1.3 on 2023-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0008_agreements_bank_name_banks_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='bank_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='banks',
            name='bank_name',
            field=models.CharField(max_length=64),
        ),
    ]
