# Generated by Django 4.1.3 on 2023-02-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0010_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amount',
            new_name='transaction_amount',
        ),
    ]
