# Generated by Django 4.1.3 on 2023-02-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0011_rename_amount_transactions_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
