# Generated by Django 4.1.3 on 2023-02-13 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0012_spendingcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mony.spendingcategories'),
        ),
    ]
