# Generated by Django 4.1.3 on 2023-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0013_transactions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreements',
            name='image_url',
            field=models.CharField(default='miauw', max_length=256),
            preserve_default=False,
        ),
    ]
