# Generated by Django 4.1.3 on 2023-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0014_agreements_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='image_url',
            field=models.CharField(default='miawu', max_length=256),
            preserve_default=False,
        ),
    ]
