# Generated by Django 4.1.3 on 2023-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0015_banks_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='requisition_id',
            field=models.CharField(default='miauw', max_length=64),
            preserve_default=False,
        ),
    ]
