# Generated by Django 4.1.3 on 2023-03-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mony', '0016_transactions_requisition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingcategories',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
